{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: neo4j
  ports:
    - port: {{ .Values.neo4j.boltPort }}
      targetPort: {{ .Values.neo4j.boltPort }}
      name: bolt
    - port: {{ .Values.neo4j.httpPort }}
      targetPort: {{ .Values.neo4j.httpPort }}
      name: http
{{- end }}
