{{- if .Values.reranker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vllm-rerank
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vllm-rerank
  ports:
    - port: {{ .Values.reranker.port }}
      targetPort: {{ .Values.reranker.port }}
      name: http
{{- end }}
